language: go

go:
    - 1.5
    - 1.6

before_install:
    - go get github.com/tools/godep

install:
    - go get -v github.com/onsi/ginkgo/ginkgo
    - go get -v github.com/onsi/gomega
    - godep restore

script: ginkgo -r -v

notifications:
    email:
        on_success: change
        on_failure: always
